# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meine Modellbauseite
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Diese Seite ist erst im Aufbau.
baseurl: "/homepage" # the subpath of your site, e.g. /blog
url: "//harmol00.github.io" # the base hostname & protocol for your site
# github_username:  HarMol00
# twitter_username: HarMol00

# Build settings
markdown: kramdown
# theme: jekyll-theme-tactile
remote_theme: abhinavs/moonwalk
 
defaults:
  -
    scope:
      path: "404"
    values:
      layout: "default"
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
